title: Zach Alexander — Blog
email: index-hearty6c@icloud.com
description: >-
  Travel notes, field observations, and experiments.
baseurl: "/blog"
url: "https://alexzander73.github.io"

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed

collections:
  posts:
    output: true
